import type { Relationship, Table, TableGroup } from '../types';

export type Dialect = 'mysql' | 'postgresql' | 'sqlserver' | 'sqlite' | 'oracle';

export const DIALECT_LABELS: Record<Dialect, string> = {
  mysql: 'MySQL / MariaDB',
  postgresql: 'PostgreSQL',
  sqlserver: 'SQL Server',
  sqlite: 'SQLite',
  oracle: 'Oracle',
};

const TYPE_MAP: Record<Dialect, Record<string, string>> = {
  mysql: {
    int: 'INT', integer: 'INT', string: 'VARCHAR(255)', varchar: 'VARCHAR(255)',
    text: 'TEXT', boolean: 'TINYINT(1)', bool: 'TINYINT(1)', datetime: 'DATETIME',
    timestamp: 'TIMESTAMP', date: 'DATE', decimal: 'DECIMAL(10,2)', float: 'FLOAT',
    double: 'DOUBLE', uuid: 'CHAR(36)', json: 'JSON', money: 'DECIMAL(19,4)',
  },
  postgresql: {
    int: 'INTEGER', integer: 'INTEGER', string: 'VARCHAR(255)', varchar: 'VARCHAR(255)',
    text: 'TEXT', boolean: 'BOOLEAN', bool: 'BOOLEAN', datetime: 'TIMESTAMP',
    timestamp: 'TIMESTAMP', date: 'DATE', decimal: 'NUMERIC(10,2)', float: 'REAL',
    double: 'DOUBLE PRECISION', uuid: 'UUID', json: 'JSONB', money: 'NUMERIC(19,4)',
  },
  sqlserver: {
    int: 'INT', integer: 'INT', string: 'NVARCHAR(255)', varchar: 'NVARCHAR(255)',
    text: 'NVARCHAR(MAX)', boolean: 'BIT', bool: 'BIT', datetime: 'DATETIME2',
    timestamp: 'DATETIME2', date: 'DATE', decimal: 'DECIMAL(10,2)', float: 'FLOAT',
    double: 'FLOAT', uuid: 'UNIQUEIDENTIFIER', json: 'NVARCHAR(MAX)', money: 'MONEY',
  },
  sqlite: {
    int: 'INTEGER', integer: 'INTEGER', string: 'TEXT', varchar: 'TEXT', text: 'TEXT',
    boolean: 'INTEGER', bool: 'INTEGER', datetime: 'TEXT', timestamp: 'TEXT', date: 'TEXT',
    decimal: 'REAL', float: 'REAL', double: 'REAL', uuid: 'TEXT', json: 'TEXT', money: 'REAL',
  },
  oracle: {
    int: 'NUMBER(10)', integer: 'NUMBER(10)', string: 'VARCHAR2(255)', varchar: 'VARCHAR2(255)',
    text: 'CLOB', boolean: 'NUMBER(1)', bool: 'NUMBER(1)', datetime: 'TIMESTAMP',
    timestamp: 'TIMESTAMP', date: 'DATE', decimal: 'NUMBER(10,2)', float: 'BINARY_FLOAT',
    double: 'BINARY_DOUBLE', uuid: 'VARCHAR2(36)', json: 'CLOB', money: 'NUMBER(19,4)',
  },
};

function quote(name: string, dialect: Dialect) {
  const safe = name.replace(/\s+/g, '_');
  switch (dialect) {
    case 'mysql':
      return `\`${safe}\``;
    case 'sqlserver':
      return `[${safe}]`;
    case 'postgresql':
    case 'oracle':
    case 'sqlite':
    default:
      return `"${safe}"`;
  }
}

function mapType(type: string, dialect: Dialect) {
  if (!type) return dialect === 'sqlite' ? 'TEXT' : 'VARCHAR(255)';
  const base = type.split(/[( ]/)[0].toLowerCase();
  if (type.includes('(')) {
    const mapped = TYPE_MAP[dialect][base];
    if (mapped && mapped.includes('(')) return type.toUpperCase();
    return (mapped ?? base.toUpperCase()) + type.slice(type.indexOf('('));
  }
  return TYPE_MAP[dialect][base] ?? type.toUpperCase();
}

function autoIncrement(dialect: Dialect, isPk: boolean) {
  switch (dialect) {
    case 'mysql':
      return 'AUTO_INCREMENT';
    case 'sqlserver':
      return 'IDENTITY(1,1)';
    case 'sqlite':
      return isPk ? 'AUTOINCREMENT' : '';
    case 'oracle':
      return 'GENERATED BY DEFAULT AS IDENTITY';
    default:
      return '';
  }
}

export function generateSQL(
  tables: Table[],
  relationships: Relationship[],
  dialect: Dialect,
  opts: { dropIfExists: boolean; groups?: TableGroup[] } = { dropIfExists: false },
): string {
  if (!tables.length) return '-- Nenhuma tabela definida ainda.';
  const q = (n: string) => quote(n, dialect);
  const out: string[] = [
    `-- ${DIALECT_LABELS[dialect]}`,
    `-- Gerado por QuickDBD Studio em ${new Date().toLocaleString('pt-BR')}`,
    '',
  ];

  // Tabelas em ordem de grupo (agrupadas), depois as sem grupo. Mantém a
  // ordem original dentro de cada bloco.
  const groups = opts.groups ?? [];
  const groupOf = new Map<string, TableGroup>();
  for (const g of groups) for (const m of g.members) if (!groupOf.has(m)) groupOf.set(m, g);
  const ordered: { table: Table; group: TableGroup | null }[] = [];
  for (const g of groups) {
    for (const t of tables) if (groupOf.get(t.name) === g) ordered.push({ table: t, group: g });
  }
  for (const t of tables) if (!groupOf.has(t.name)) ordered.push({ table: t, group: null });
  const orderedTables = ordered.map((o) => o.table);

  if (opts.dropIfExists) {
    for (const t of [...orderedTables].reverse()) {
      out.push(
        dialect === 'sqlserver'
          ? `DROP TABLE IF EXISTS ${q(t.name)};`
          : `DROP TABLE IF EXISTS ${q(t.name)}${dialect === 'postgresql' ? ' CASCADE' : ''};`,
      );
    }
    out.push('');
  }

  let lastGroup: TableGroup | null | undefined = undefined;
  for (const { table, group } of ordered) {
    if (group !== lastGroup) {
      if (group) {
        const bar = '='.repeat(Math.max(8, group.name.length + 12));
        out.push(`-- ${bar}`, `-- Grupo: ${group.name}`, `-- ${bar}`, '');
      } else if (lastGroup !== undefined) {
        out.push('-- ============', '-- Sem grupo', '-- ============', '');
      }
      lastGroup = group;
    }
    const defs: string[] = [];
    const pks = table.columns.filter((c) => c.pk);

    for (const col of table.columns) {
      let def = `    ${q(col.name)} `;
      if (dialect === 'postgresql' && col.increment) {
        def += col.type.toLowerCase().includes('big') ? 'BIGSERIAL' : 'SERIAL';
      } else {
        def += mapType(col.type, dialect);
        if (col.increment) {
          const ai = autoIncrement(dialect, col.pk);
          if (ai) def += ` ${ai}`;
        }
      }
      if (col.pk && pks.length === 1 && dialect !== 'sqlite') def += ' PRIMARY KEY';
      if (col.pk && pks.length === 1 && dialect === 'sqlite') {
        def += ' PRIMARY KEY';
        if (col.increment) def += ' AUTOINCREMENT';
      }
      if (!col.pk && !col.nullable) def += ' NOT NULL';
      if (col.unique && !col.pk) def += ' UNIQUE';
      if (col.defaultValue !== undefined) {
        const v = col.defaultValue;
        const numeric = /^-?\d+(\.\d+)?$/.test(v) || /^(true|false|null|current_timestamp|now\(\))$/i.test(v);
        def += ` DEFAULT ${numeric ? v.toUpperCase() : `'${v}'`}`;
      }
      if (col.note && dialect === 'mysql') def += ` COMMENT '${col.note.replace(/'/g, "''")}'`;
      defs.push(def);
    }

    if (pks.length > 1) {
      defs.push(`    PRIMARY KEY (${pks.map((c) => q(c.name)).join(', ')})`);
    }

    out.push(`CREATE TABLE ${q(table.name)} (`);
    out.push(defs.join(',\n'));
    out.push(');');
    out.push('');

    for (const col of table.columns) {
      if (col.index && !col.pk && !col.unique) {
        out.push(
          `CREATE INDEX ${q(`idx_${table.name}_${col.name}`)} ON ${q(table.name)} (${q(col.name)});`,
        );
      }
    }
  }

  if (relationships.length) {
    out.push('');
    out.push('-- Chaves estrangeiras');
    for (const rel of relationships) {
      out.push(
        `ALTER TABLE ${q(rel.fromTable)} ADD CONSTRAINT ${q(
          `fk_${rel.fromTable}_${rel.fromColumn}`,
        )}\n    FOREIGN KEY (${q(rel.fromColumn)}) REFERENCES ${q(rel.toTable)} (${q(rel.toColumn)});`,
      );
    }
  }

  return out.join('\n') + '\n';
}

export function generateMarkdown(
  tables: Table[],
  relationships: Relationship[],
  groups: TableGroup[] = [],
): string {
  const out: string[] = ['# Dicionário de dados', ''];
  if (groups.length) {
    out.push('## Grupos', '');
    for (const g of groups) {
      out.push(`- **${g.name}**: ${g.members.length ? g.members.map((m) => `\`${m}\``).join(', ') : '_vazio_'}`);
    }
    out.push('');
  }
  const groupOf = new Map<string, string>();
  for (const g of groups) for (const m of g.members) if (!groupOf.has(m)) groupOf.set(m, g.name);
  for (const t of tables) {
    const gname = groupOf.get(t.name);
    out.push(`## ${t.name}${gname ? ` <sub>· ${gname}</sub>` : ''}`, '');
    out.push('| Coluna | Tipo | Chave | Nulo | Padrão |');
    out.push('| --- | --- | --- | --- | --- |');
    for (const c of t.columns) {
      const keys = [c.pk ? 'PK' : '', c.fk ? 'FK' : '', c.unique ? 'UNIQUE' : '']
        .filter(Boolean)
        .join(', ');
      out.push(
        `| ${c.name} | ${c.type || '-'} | ${keys || '-'} | ${c.nullable ? 'sim' : 'não'} | ${
          c.defaultValue ?? '-'
        } |`,
      );
    }
    out.push('');
  }
  if (relationships.length) {
    out.push('## Relacionamentos', '');
    for (const r of relationships) {
      out.push(`- \`${r.fromTable}.${r.fromColumn}\` → \`${r.toTable}.${r.toColumn}\` (${r.fromCard} → ${r.toCard})`);
    }
  }
  return out.join('\n');
}
